# scripts/post_pr_comment.py
# Reads the CI summary JSON and posts a formatted comment to the GitHub PR.
# Called by the GitHub Actions workflow after ci_runner.py completes.
#
# Usage:
#   python scripts/post_pr_comment.py \
#     --summary  data/findings/ci_summary_<sha>.json \
#     --repo     owner/repo-name \
#     --pr       123 \
#     --token    $GITHUB_TOKEN

import argparse
import json
import os
import sys
import urllib.request
import urllib.error


PRIORITY_ICONS = {
    "CRITICAL": "🔴",
    "HIGH":     "🟠",
    "MEDIUM":   "🟡",
    "LOW":      "🟢",
    "INFO":     "⚪",
}


def post_comment(repo, pr_number, token, body):
    """Post a comment to a GitHub PR via the REST API."""
    url = f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments"
    payload = json.dumps({"body": body}).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=payload,
        headers={
            "Authorization": f"Bearer {token}",
            "Accept":        "application/vnd.github+json",
            "Content-Type":  "application/json",
            "X-GitHub-Api-Version": "2022-11-28",
        },
        method="POST"
    )
    try:
        with urllib.request.urlopen(req) as resp:
            print(f"[INFO] Comment posted — HTTP {resp.status}")
            return True
    except urllib.error.HTTPError as e:
        print(f"[ERROR] GitHub API error: {e.code} {e.reason}")
        print(e.read().decode())
        return False


def build_comment(summary):
    commit_sha  = summary.get("commit_sha", "unknown")
    short_sha   = summary.get("short_sha",  commit_sha[:8])
    total       = summary.get("total", 0)
    by_priority = summary.get("by_priority", {})
    blocked     = summary.get("blocked", False)

    status_line = (
        "## 🚨 Security Scan — PR Blocked\n"
        "> CRITICAL findings must be resolved before this PR can merge."
        if blocked else
        "## ✅ Security Scan — Passed"
    )

    rows = ""
    for priority in ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]:
        count = by_priority.get(priority, 0)
        if count:
            icon  = PRIORITY_ICONS.get(priority, "")
            block = " ← **PR blocked**" if priority == "CRITICAL" else ""
            rows += f"| {icon} {priority} | {count} |{block}\n"

    if not rows:
        rows = "| — | No findings detected |\n"

    comment = f"""{status_line}

**Commit:** `{short_sha}` &nbsp;|&nbsp; **Total findings:** {total}

| Severity | Count |
|----------|-------|
{rows}
---
<sub>Generated by SecurePipeline Hub · Scanners: Semgrep · Gitleaks · Trivy</sub>
"""
    return comment.strip()


def main():
    parser = argparse.ArgumentParser(
        description="Post CI scan summary as a GitHub PR comment"
    )
    parser.add_argument('--summary', required=True, help="Path to ci_summary_<sha>.json")
    parser.add_argument('--repo',    required=True, help="GitHub repo e.g. owner/repo")
    parser.add_argument('--pr',      required=True, help="PR number")
    parser.add_argument('--token',   default=os.environ.get('GITHUB_TOKEN', ''),
                        help="GitHub token (defaults to GITHUB_TOKEN env var)")
    args = parser.parse_args()

    if not args.token:
        print("[ERROR] No GitHub token provided. Set GITHUB_TOKEN or pass --token.")
        sys.exit(1)

    if not os.path.exists(args.summary):
        print(f"[ERROR] Summary file not found: {args.summary}")
        sys.exit(1)

    with open(args.summary) as f:
        summary = json.load(f)

    body = build_comment(summary)
    print("[INFO] Comment preview:")
    print("-" * 40)
    print(body)
    print("-" * 40)

    success = post_comment(args.repo, args.pr, args.token, body)
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()